### ISSUE TITLE
Consistent method for connecting nb servers to github repos

### ISSUE THREAD

**Issue by crobby** [thoth-station/s2i-generic-data-science-notebook#1]
**Is your feature request related to a problem? Please describe.**
As a DS user, I need to connect my NB server to a GitHub repo so I can pull files from or push files to an existing repo that I use for my data science project.

**Describe the solution you'd like**
Ideally, we have a simple way that will give us the desired functionality built-in to our notebook servers so that we can give a consistent user experience.

**Describe alternatives you've considered**
We have other images that utilize Elyra.  If it's possible to backport the solution there, that might be a win, but we are open to ideas.

**Additional context**

**Comment by fridex** [comment]
CC @vpavlin, IIRC Vasek did some work around this.

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> As a DS user, I need to connect my NB server to a GitHub repo so I can pull files from or push files to an existing repo that I use for my data science project.
> 
> **Describe the solution you'd like**
> Ideally, we have a simple way that will give us the desired functionality built-in to our notebook servers so that we can give a consistent user experience.
> 
> **Describe alternatives you've considered**
> We have other images that utilize Elyra. If it's possible to backport the solution there, that might be a win, but we are open to ideas.
> 
> **Additional context**

HI @crobby , 
the git extension used in Elyra is available standalone for jupyterlab [1], so it can be installed with pip. 

It is already migrated to jupyterlab3 and it can be used without rebuilding jupyterlab (differently from what happens with Elyra extension). If your goal is to have only the git extension in jupyterlab, we could try having that in the image without Elyra.

References:[1] https://github.com/jupyterlab/jupyterlab-git

cc @harshad16

**Comment by pacospace** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > As a DS user, I need to connect my NB server to a GitHub repo so I can pull files from or push files to an existing repo that I use for my data science project.
> > **Describe the solution you'd like**
> > Ideally, we have a simple way that will give us the desired functionality built-in to our notebook servers so that we can give a consistent user experience.
> > **Describe alternatives you've considered**
> > We have other images that utilize Elyra. If it's possible to backport the solution there, that might be a win, but we are open to ideas.
> > **Additional context**
> 
> HI @crobby , 
> the git extension used in Elyra is available standalone for jupyterlab [1], so it can be installed with pip. 
> 
> It is already migrated to jupyterlab3 and it can be used without rebuilding jupyterlab (differently from what happens with Elyra extension). If your goal is to have only the git extension in jupyterlab, we could try having that in the image without Elyra.
> 
> References:[1] https://github.com/jupyterlab/jupyterlab-git
> 
> cc @harshad16

Based on the user story it seems to be a feasible solution, having Jupyterlab + jupyterlab-git extension. 

I re checked version and it is in beta release: jupyterlab-git==0.30.0b1, the stable version should come soon and we can follow this thread: https://github.com/jupyterlab/jupyterlab-git/issues/779

**Comment by goern** [comment]
/kind feature
/priority important-soon

@pacospace could you take care of this issue?

**Comment by pacospace** [comment]
@harshad16 I was thinking for this feature to add `jupyterlab-git` in this Pipfile, not in the minimal notebook, because it might create issue with jupyterlab-git installed with Elyra, WDYT? Or actually we should add that to assemble script as it is not an application packages required.

**Comment by pacospace** [comment]
> @harshad16 I was thinking for this feature to add `jupyterlab-git` in this Pipfile, not in the minimal notebook, because it might create issue with jupyterlab-git installed with Elyra, WDYT? or should we do that in assembe script?

**Comment by crobby** [comment]
Anyone have any updates or further thoughts on this issue?

**Comment by harshad16** [comment]
As @pacospace suggested, let's install the jupyterlab-git in the generic-data-science-notebook and see if it serves the purpose.
personally, I don't have experience in the usage of such a package, so it is worth trying.
we would make the first release and we can test this out

**Comment by harshad16** [comment]
As the package jupyterlab-git is in beta release version, we would be installing that one for now https://pypi.org/project/jupyterlab-git/0.30.0b2/

**Comment by crobby** [comment]
Ok, that sounds good.  Let me and @tmckayus know when this is in so we can be sure to have our builds in order.  Thanks

**Comment by harshad16** [comment]
@crobby  are we planning to build these images through cpaas as well?

**Comment by crobby** [comment]
Yes, that is the plan.

**Comment by crobby** [comment]
Is this still in-flight?  Ideally, this can get in sooner rather than later so we can use it in testing.

**Comment by pacospace** [comment]
> Is this still in-flight? Ideally, this can get in sooner rather than later so we can use it in testing.

hey @crobby, we need to merge https://github.com/thoth-station/s2i-generic-data-science-notebook/pull/6 and make a new release of this image. cc @harshad16

**Comment by harshad16** [comment]
This was added last week @pacospace  and @crobby 
The release can be found at https://quay.io/repository/thoth-station/s2i-generic-data-science-notebook?tab=tags
I had passed the image to @LaVLaS as well

**Comment by pacospace** [comment]
> This was added last week @pacospace and @crobby
> The release can be found at https://quay.io/repository/thoth-station/s2i-generic-data-science-notebook?tab=tags
> I had passed the image to @LaVLaS as well

jupyterlab-git extension need to be https://pypi.org/project/jupyterlab-git/0.30.0b2/

```
podman run -it quay.io/thoth-station/s2i-generic-data-science-notebook:v0.0.1  pip show jupyterlab-git 
Name: jupyterlab-git
Version: 0.23.3
Summary: A server extension for JupyterLab's git extension
Home-page: https://github.com/jupyterlab/jupyterlab-git
Author: Jupyter Development Team
Author-email: None
License: BSD
Location: /opt/app-root/lib/python3.8/site-packages
Requires: pexpect, nbdime, notebook, packaging
Required-by: 

```
