### ISSUE TITLE
Include jupyterlab-s3-browser extension

### ISSUE THREAD

**Issue by MichaelClifford** [thoth-station/s2i-generic-data-science-notebook#15]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to use the s3cmd command line tool to see what's in my remote storage. It would be great if I could navigate ceph the same way I navigate my PVC files.   

**Describe the solution you'd like**

I would like the [jupyterlab-s3-browser extension](https://github.com/IBM/jupyterlab-s3-browser) added to the jupyterlab notebooks. 

**Describe alternatives you've considered**

No other alternatives have been proposed for GUI lab/notebook s3 exploration. There are CLI tools, python API's and the Hue S3 browser. However, I think this lab extension is far faster, easier and more reliable to use than all of these alternatives.  

**Additional context**

**Comment by harshad16** [comment]
version v0.0.3 has the required changes.
This pr should close this issue. https://github.com/opendatahub-io/odh-manifests/pull/394

**Comment by goern** [comment]
looks like the upstream issue is closed/merged, feel free to re-open if required

/close
