### ISSUE TITLE
R & Julia included in the generic data science notebook image?

### ISSUE THREAD

**Issue by ViitasaariVille** [thoth-station/s2i-generic-data-science-notebook#43]
Hi, this is just a suggestion. I was wondering if R (IRkernel) and Julia (IJulia) could be included in the generic notebook image? I believe this would attract some data scientists. I was playing around with R yesterday and managed to install the R notebook with these instructions: https://community.rstudio.com/t/r-in-jupyter-under-linux/18594/3. Personally, I liked the R notebook compared to e.g. R Studio.

**Comment by harshad16** [comment]
Thank you for the issue.
we would explore these options.
only thought I have is maybe the R(IRkernel) and Julia might require more installation in terms of package or tools,
so maybe it would be a good idea to have a separate image for it for ease of scalability.

**Comment by ViitasaariVille** [comment]
Yep, indeed, makes sense to have a separate image. Trying, as we speak, to install IJulia in the generic data science image. Seems to be a bit trickly behind a firewall. People with background in Matlab would probably like Julia's syntax.

**Comment by harshad16** [comment]
This one would take more time, it was not considered for Q1.
As of now, another member of our team has created custom notebook image for R. 
which can be accessed on this repo: https://github.com/guimou/custom-notebooks

for julia supported notebook we would have to wait till this work in brought up in sprint plan.
Hoping to get this done soon.
