### ISSUE TITLE
please update all deps

### ISSUE THREAD

**Issue by goern** [thoth-station/s2i-generic-data-science-notebook#48]
**Is your feature request related to a problem? Please describe.**
https://quay.io/repository/thoth-station/s2i-generic-data-science-notebook?tab=tags&tag=latest needs an update of base image and dependencies, due to
```
Quay Security Scanner has detected 30 vulnerabilities.
Patches are available for 30 vulnerabilities.
 14 High-level vulnerabilities.
 15 Medium-level vulnerabilities.
 1 Low-level vulnerabilities.
```

**Describe the solution you'd like**
Kebechet should start maintaining the container image.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

/kind feature
/priority critical-urgent
/assign @Gregory-Pereira

**Comment by harshad16** [comment]
Done with #58 
closing the issue.
