### ISSUE TITLE
Include Boto library

### ISSUE THREAD

**Issue by guimou** [thoth-station/s2i-generic-data-science-notebook#5]
In previous versions of OpenDataHub, the boto3 library, used to connect to S3 storage, was included. It was not a specific requirement, but came along as a dependancy apparently. Since 0.9, it is not available in the base image (nor in scipy or tensorflow).
As object storage is an important component of any data platform, this should definitely be brought back.
I see this as a regression as many demos or workshops took it for granted and won't work any more in this new version.
@LaVLaS @vpavlin

**Comment by goern** [comment]
@LaVLaS any update on this?

**Comment by harshad16** [comment]
boto3 is available in v0.0.1 of the generic-data-science-notebook

**Comment by goern** [comment]
@harshad16 can we close this?

**Comment by harshad16** [comment]
This feature was included and is present in all the image 
can be found on version >= v0.0.2
closing this issue
please open a new one,if found ant issue.
