### ISSUE TITLE
.aicoe-ci.yaml needs auto maintenance

### ISSUE THREAD

**Issue by goern** [thoth-station/s2i-generic-data-science-notebook#50]
**Is your feature request related to a problem? Please describe.**
container image tags should be kept up to date automatically

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

/kind feature
/priority important-soon
/triage needs-information

**Comment by harshad16** [comment]
completed with automation and pr #51
