### ISSUE TITLE
create 'Data Science base image'

### ISSUE THREAD

**Issue by goern** [thoth-station/s2i-generic-data-science-notebook#7]
As a data scientist, I need a minimal python notebook image with Python x.y.z so that I can create a vanilla notebook server from JupyterHub and write code to process or visualize data.

The notebook should also contain the following as default installed packages:

Boto3 x.y.z
Kafka-python x.y.z
Pandas x.y.z
Matplotlib x.y.z
Numpy x.y.z
Scipy x.y.z

let's restructure so that s2i-minimal --> s2i-generic-data-science -> tensorflow | pytorch | gpu | ...

seeAlso https://github.com/thoth-station/s2i-minimal-notebook/issues/22

This is upstream issue of https://issues.redhat.com/browse/RHODS-177

**Comment by harshad16** [comment]
This feature was included and is present in all the image 
can be found on version >= v0.0.2
also updated in odh-manifest: https://github.com/opendatahub-io/odh-manifests/commit/26ef3667225fd5b55c6257a7b84f9e16bbe30ed9#diff-83a4b75dff25805267eaf115040d89335cfc5231c4ca004c7a62da72a5a7f380
closing this issue
please open a new one,if found ant issue.
