### ISSUE TITLE
Introduce a plugin to make editing Python code easier

### ISSUE THREAD

**Issue by crobby** [thoth-station/s2i-generic-data-science-notebook#9]
**Is your feature request related to a problem? Please describe.**
As a user, I need to be able to easily execute Python script files so I can test the components needed for model serving.

As part of the model serving best practice template, we are recommending that users capture their predict model in a separate prediction.py file. Elyra has a Python script editor plugin that enables users to edit and run Python scripts from within JL. I think it is worthwhile to investigate the feasibility of including a Python script editor plugin to help simplify the model serving process. 

**Describe the solution you'd like**
We can include a plugin (possibly the same as Elyra?) that supports ease of Python development

**Describe alternatives you've considered**
Banging my head on the keyboard....hurts

**Additional context**

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> As a user, I need to be able to easily execute Python script files so I can test the components needed for model serving.
> 
> As part of the model serving best practice template, we are recommending that users capture their predict model in a separate prediction.py file. Elyra has a Python script editor plugin that enables users to edit and run Python scripts from within JL. I think it is worthwhile to investigate the feasibility of including a Python script editor plugin to help simplify the model serving process.
> 
> **Describe the solution you'd like**
> We can include a plugin (possibly the same as Elyra?) that supports ease of Python development
> 
> **Describe alternatives you've considered**
> Banging my head on the keyboard....hurts
> 
> **Additional context**

Hey @crobby, that plugin is coming with Elyra, but not sure if there is a package like jupyterlab-git that we can add. Not sure if they plan to separate that to make an independent jupyterlab extension.

**Comment by crobby** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > As a user, I need to be able to easily execute Python script files so I can test the components needed for model serving.
> > As part of the model serving best practice template, we are recommending that users capture their predict model in a separate prediction.py file. Elyra has a Python script editor plugin that enables users to edit and run Python scripts from within JL. I think it is worthwhile to investigate the feasibility of including a Python script editor plugin to help simplify the model serving process.
> > **Describe the solution you'd like**
> > We can include a plugin (possibly the same as Elyra?) that supports ease of Python development
> > **Describe alternatives you've considered**
> > Banging my head on the keyboard....hurts
> > **Additional context**
> 
> Hey @crobby, that plugin is coming with Elyra, but not sure if there is a package like jupyterlab-git that we can add. Not sure if they plan to separate that to make an independent jupyterlab extension.

That's a good point.  I think we'd be happy with anything that is relatively easy to get in there, but I don't have any specific plugins in mind.

**Comment by harshad16** [comment]
Threadlink: https://chat.google.com/room/AAAA9x27brI/xNGzzEDfv-A

**Comment by harshad16** [comment]
References:
https://elyra.readthedocs.io/en/latest/getting_started/installation.html
`The Python editor feature can optionally be installed as a stand-alone extension`. on https://elyra.readthedocs.io/en/latest/getting_started/overview.html#python-and-r-scripts-execution-support

**Comment by harshad16** [comment]
This feature is available in version v0.0.4
should be available in odh soon with: https://github.com/opendatahub-io/odh-manifests/pull/437
